version: "3.7"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    ports:
      - $DB_HOST:$DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
