// Package models contains the types for schema 'public'.
package models

import "github.com/google/uuid"

// Code generated by xo. DO NOT EDIT.

// PersonById represents a row from '[custom person_by_id]'.
type PersonById struct {
	Name  string // name
	Email string // email
}

// PersonByIdsByPersonId runs a custom query, returning results as PersonById.
func PersonByIdsByPersonId(db XODB, personId uuid.UUID) ([]*PersonById, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`name, ` + // ::text AS name
		`email ` + // ::text AS email
		`FROM person ` +
		`WHERE ` +
		`id = $1`

	// run query
	XOLog(sqlstr, personId)
	q, err := db.Query(sqlstr, personId)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*PersonById{}
	for q.Next() {
		pb := PersonById{}

		// scan
		err = q.Scan(&pb.Name, &pb.Email)
		if err != nil {
			return nil, err
		}

		res = append(res, &pb)
	}

	return res, nil
}
